In [10]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split


# Part 1: Load the dataset
## Load the dataset (load remotely, not locally)
## Output the first 15 rows of the data
## Display a summary of the table information (number of datapoints, etc.)

In [11]:
from sklearn.datasets import load_iris
iris = load_iris()
#convert the dataset to pandas data frame
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
#display first 15 datasets
iris_df.head(15)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
1                 4.9               3.0                1.4               0.2
2                 4.7               3.2                1.3               0.2
3                 4.6               3.1                1.5               0.2
4                 5.0               3.6                1.4               0.2
5                 5.4               3.9                1.7               0.4
6                 4.6               3.4                1.4               0.3
7                 5.0               3.4                1.5               0.2
8                 4.4               2.9                1.4               0.2
9                 4.9               3.1                1.5               0.1
10                5.4               3.7                1.5               0.2
11                4.8               3.4                1.6               0.2
12                4.8               3.0                1.4               0.1
13                4.3               3.0                1.1               0.1
14                5.8               4.0                1.2               0.2

In [12]:
#display dataset info
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [13]:
#The features are the sepal length, width and petal length, width. The label is the classes setosa, versicolor, and virginica.

# Part 2: Split the dataset into train and test
## Take the dataset and split it into our features (X) and label (y)

## Use sklearn to split the features and labels into a training/test set. (90% train, 10% test)

In [14]:
#set the features and label.
X = iris.data
y = iris.target

In [15]:
#split the data into training and testing set.
X_train, X_test,y_train, y_test = train_test_split(X,y, test_size=0.1)

# Part 3: Logistic Regression
## i. Use sklearn to train a LogisticRegression model on the training set

## ii. For a sample datapoint, predict the probabilities for each possible class

## iii. Report on the score for Logistic regression model, what does the score measure?

## iv. Extract the coefficents and intercepts for the boundary line(s)

In [21]:
from sklearn.linear_model import LogisticRegression
#Train the model using the training dataset
LR = LogisticRegression(solver='lbfgs', max_iter=1000).fit(X_train,y_train)
LR.predict(X_train)

array([0, 2, 0, 2, 0, 2, 2, 2, 0, 0, 1, 2, 2, 0, 0, 0, 2, 2, 0, 2, 1, 2,
       0, 2, 1, 2, 1, 1, 0, 2, 0, 1, 1, 2, 2, 0, 0, 2, 0, 0, 0, 1, 2, 0,
       0, 1, 2, 1, 2, 0, 1, 0, 0, 1, 2, 2, 1, 0, 2, 0, 0, 2, 0, 0, 2, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 2, 0, 1, 2, 0, 0, 0, 0, 1, 1, 1, 2, 1,
       0, 2, 0, 0, 2, 1, 0, 2, 0, 2, 1, 2, 1, 1, 2, 2, 1, 2, 1, 1, 1, 0,
       2, 1, 2, 2, 2, 1, 2, 1, 0, 0, 2, 1, 1, 2, 2, 2, 1, 2, 0, 1, 1, 2,
       2, 1, 1])

In [93]:
LR.predict_proba(X_test)

array([[9.65027568e-03, 8.85622612e-01, 1.04727112e-01],
       [1.11676136e-02, 7.55291307e-01, 2.33541079e-01],
       [6.06532620e-03, 7.96798930e-01, 1.97135744e-01],
       [9.65187530e-01, 3.48123954e-02, 7.44788387e-08],
       [2.51421547e-03, 7.90643654e-01, 2.06842130e-01],
       [1.62270887e-06, 3.60688687e-02, 9.63929509e-01],
       [9.60244611e-01, 3.97552545e-02, 1.34066747e-07],
       [9.06661379e-06, 2.36671250e-02, 9.76323808e-01],
       [9.23013464e-03, 9.26042268e-01, 6.47275975e-02],
       [9.85550326e-01, 1.44496257e-02, 4.85092758e-08],
       [9.84895214e-01, 1.51047577e-02, 2.85828416e-08],
       [1.23278280e-03, 4.59035978e-01, 5.39731240e-01],
       [4.45084527e-02, 9.00439343e-01, 5.50522044e-02],
       [9.45090117e-05, 1.50740586e-01, 8.49164905e-01],
       [9.41117119e-01, 5.88826808e-02, 2.00184717e-07]])

In [23]:
LR.score(X_train,y_train)

0.9703703703703703

In [25]:
#The score of the Logistic Regression model shows the accuracy of the predictions.

In [26]:
#coefficents
LR.coef_

array([[-0.43670428,  0.94180042, -2.415941  , -1.0260266 ],
       [ 0.56696434, -0.41474456, -0.2078736 , -0.88258642],
       [-0.13026006, -0.52705586,  2.6238146 ,  1.90861302]])

In [27]:
#Intercepts
LR.intercept_

array([  9.51333941,   2.15185864, -11.66519805])

# Part 4: Support Vector Machine
## i. Use sklearn to train a Support Vector Classifier on the training set

## ii. For a sample datapoint, predict the probabilities for each possible class

## iii. Report on the score for the SVM, what does the score measure?

In [100]:
from sklearn import svm
clf = svm.SVC(probability=True)
clf.fit(X_train,y_train)

SVC(probability=True)

In [101]:
clf.predict_proba(X_test)

array([[0.00655557, 0.95838443, 0.03506   ],
       [0.01047383, 0.90080214, 0.08872402],
       [0.00687882, 0.91344402, 0.07967716],
       [0.96675591, 0.02330373, 0.00994037],
       [0.00889603, 0.8719541 , 0.11914987],
       [0.00934942, 0.00451554, 0.98613504],
       [0.95842954, 0.0301292 , 0.01144126],
       [0.00738693, 0.00392873, 0.98868434],
       [0.00833008, 0.97700712, 0.01466281],
       [0.97512263, 0.01575892, 0.00911846],
       [0.97770582, 0.013905  , 0.00838917],
       [0.00936385, 0.4696716 , 0.52096455],
       [0.01289054, 0.97313322, 0.01397623],
       [0.00856315, 0.05240465, 0.9390322 ],
       [0.94935763, 0.03807127, 0.0125711 ]])

In [46]:
clf.predict([[5.8,5.6,1.2,0.2]])

array([0])

In [47]:
clf.score(X_train,y_train)

0.9703703703703703

In [48]:
clf.score(X_test,y_test)

1.0

In [49]:
#The score of the SVM means the accuracy of the prediction in the multi-label classification.

# Part 5: Neural Network
## i. Use sklearn to train a Neural Network (MLP Classifier) on the training set

## ii. For a sample datapoint, predict the probabilities for each possible class

## iii. Report on the score for the Neural Network, what does the score measure?

## iv: Experiment with different options for the neural network, report on your best configuration (the highest score I was able to achieve was 0.8666)

In [72]:
from sklearn.neural_network import MLPClassifier
MLPC = MLPClassifier(random_state=39, max_iter=1000).fit(X_train, y_train)

In [96]:
MLPC.predict_proba(X_test)

array([[3.91227623e-02, 5.76122367e-01, 3.84754871e-01],
       [4.74461486e-02, 5.71105565e-01, 3.81448286e-01],
       [3.54489782e-02, 5.52353226e-01, 4.12197796e-01],
       [9.19980918e-01, 7.88186330e-02, 1.20044928e-03],
       [3.31928609e-02, 5.39967317e-01, 4.26839822e-01],
       [2.53523263e-03, 2.44810195e-01, 7.52654572e-01],
       [9.24638348e-01, 7.41992667e-02, 1.16238524e-03],
       [4.05419800e-03, 2.80445167e-01, 7.15500636e-01],
       [5.77856792e-02, 6.09132981e-01, 3.33081340e-01],
       [9.33733375e-01, 6.53386298e-02, 9.27995453e-04],
       [9.47727479e-01, 5.16530525e-02, 6.19468876e-04],
       [1.67783223e-02, 4.57440171e-01, 5.25781506e-01],
       [7.43274679e-02, 6.33911389e-01, 2.91761144e-01],
       [6.84686619e-03, 3.49313521e-01, 6.43839613e-01],
       [9.12910145e-01, 8.56205325e-02, 1.46932246e-03]])

In [74]:
MLPC.predict([[2.8,7.5,3.6,0.5]])

array([0])

In [75]:
MLPC.predict([[6.1,3.2,8.4,2.1]])

array([2])

In [76]:
MLPC.score(X_train,y_train)

0.9777777777777777

In [77]:
MLPC.score(X_test,y_test)

1.0

In [78]:
#The score represents the accuracy of the multi-label classification, mainly the accuracy of predicting each label.

In [81]:
MLPC = MLPClassifier(random_state=100, solver='lbfgs',max_iter=1000).fit(X_train, y_train)
MLPC.score(X_train,y_train)

0.9851851851851852

In [83]:
MLPC = MLPClassifier(random_state=100, solver='sgd',max_iter=2000).fit(X_train, y_train)
MLPC.score(X_train,y_train)

0.9703703703703703

In [84]:
MLPC = MLPClassifier(random_state=100, solver='lbfgs', activation='logistic',max_iter=1000).fit(X_train, y_train)
MLPC.score(X_train,y_train)

1.0

In [87]:
MLPC = MLPClassifier(random_state=100, solver='sgd', activation='logistic',max_iter=3000).fit(X_train, y_train)
MLPC.score(X_train,y_train)

0.9703703703703703

In [88]:
#The highest score I got is 1 with solver='lbfgs', activation='logistic', 1000 iterations

# Part 6: K-Nearest Neighbors
## i. Use sklearn to 'train' a k-Neighbors Classifier
## Note: KNN is a nonparametric model and technically doesn't require training
## fit will essentially load the data into the model see link below for more information
## https://stats.stackexchange.com/questions/349842/why-do-we-need-to-fit-a-k-nearest-neighbors-classifier

## ii. For a sample datapoint, predict the probabilities for each possible class

## iii. Report on the score for kNN, what does the score measure?

In [89]:
from sklearn.neighbors import KNeighborsClassifier
KN = KNeighborsClassifier(n_neighbors=3)
KN.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [102]:
KN.predict_proba(X_test)

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [91]:
KN.predict([[9.6,0.2,1.6,3.6]])

array([1])

In [92]:
KN.predict([[2.7,5.9,2.8,6.2]])

array([2])

In [103]:
KN.score(X_train,y_train)

0.9555555555555556

In [104]:
#The score returns the accuracy of Kneighbors. Althought it's not the highest, it is still a high score.

# Part 7: Conclusions and takeaways
## In your own words describe the results of the notebook. Which model(s) performed the best on the dataset? Why do you think that is? Did anything surprise you about the exercise?

In [105]:
#In this assignemnt,we had four different model/classifiers. 
#Based on the result of the iris dataset, logisticregression and MLPC are not the best for the dataset. 
#Althought they all had a high score, but the result of the prediction probability is terrible.
#SVM and kneighbor both scored >0/95 also did well in the prediction probability. 
#Kneighbor had very definite results for the predictions and SVM gave 80-90% probability for each prediction.
#It won't make any difference between SVM or Kneighbor if the results are accurate, however if there is any error in the prediction, 
#Kneighbor will seems too definite unlike SVM gave a little chance for the dataset to be another label. 
#I am surpriced with the prediction probability given by Kneighbor it is very hard to predict something with 100% correct.